<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Spectre.Console.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Kuroe.Cli\Kuroe.Cli.csproj" />
    <ProjectReference Include="..\Kuroe.TestSupport\Kuroe.TestSupport.csproj" />
  </ItemGroup>

</Project>