<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ApiHub" />
    <PackageReference Include="ApiHub.ChatClient" />
    <PackageReference Include="ApiHub.Json" />
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
