<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ApiHub" />
    <PackageReference Include="ApiHub.ChatClient" />
    <PackageReference Include="ApiHub.Json" />
    <PackageReference Include="ApiHub.Shared" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Extensions.AI" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kuroe.Shared\Kuroe.Shared.csproj" />
  </ItemGroup>

</Project>
